# Build aşaması
FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

# Çalıştırma aşaması (Burası değişti)
FROM eclipse-temurin:17-jdk-jammy
COPY --from=build /target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]